version: '3'
services:
    web:
        image: nginx:latest
        ports:
            - '80:80'
        links:
            - php

        volumes:
            - ./..:/code
            - ./nginx.conf.d/backend.local.conf:/etc/nginx/conf.d/default.conf

    php:
        build: 'php'
        volumes:
            - ./..:/code
